-- USUARIO
CREATE TABLE IF NOT EXISTS USUARIO(
	ID_USUARIO SERIAL PRIMARY KEY,
	NM_USUARIO VARCHAR(50) NOT NULL,
    NM_EMAIL VARCHAR(100),
    ID_EMPREEDIMENTO INTEGER,
    FL_ATIVO BOOLEAN,
	DT_CRIACAO TIMESTAMP WITH TIME ZONE NOT NULL,
	DT_ATUALIZACAO TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS USUARIO_ACESSO(
	ID_USUARIO_ACESSO SERIAL PRIMARY KEY,
	NM_USUARIO_ACESSO VARCHAR(150) NOT NULL,
	DS_CRIPT_SENHA VARCHAR(300) NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	FL_ATIVO BOOLEAN NOT NULL,
	DT_CRIACAO TIMESTAMP WITH TIME ZONE NOT NULL,
	DT_ATUALIZACAO TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS USUARIO_SESSAO(
	ID_USUARIO_SESSAO SERIAL PRIMARY KEY,
	CD_UUID_SESSAO VARCHAR(80) NOT NULL,
	ID_USUARIO_ACESSO INTEGER NOT NULL,
	FL_ATIVO BOOLEAN NOT NULL,
	DT_CRIACAO TIMESTAMP WITH TIME ZONE NOT NULL,
	DT_ATUALIZACAO TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS TEMPLATE_EMAIL(
	ID_TEMPLATE_EMAIL SERIAL PRIMARY KEY,
	NM_TITULO_TEMPLATE VARCHAR(50) NOT NULL,
	DS_TEMPLATE VARCHAR(10000) NOT NULL,
	DT_CRIACAO TIMESTAMP WITH TIME ZONE NOT NULL,
	DT_ATUALIZACAO TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS VARIAVEL_TEMPLATE_EMAIL(
	ID_VARIAVEL_TEMPLATE_EMAIL SERIAL PRIMARY KEY,
	ID_TEMPLATE_EMAIL INTEGER,
	NM_TITULO_VARIAVEL VARCHAR(50) NOT NULL,
	KEY_VARIAVEL VARCHAR(50) NOT NULL,
	DT_CRIACAO TIMESTAMP WITH TIME ZONE NOT NULL
);